server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod

management:
  endpoint:
    health:
      show-details: when-authorized

# Prod environment specific settings can go here.

storage:
  provider: s3
  s3:
    # endpoint: https://s3.your-region.amazonaws.com
    # region: your-region
    # access-key: your-access-key
    # secret-key: your-secret-key
    # bucket-name: your-bucket-name
    # url-prefix: https://cdn.yourdomain.com
    path-style-access-enabled: false
    expiration: 15m

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
